### ISSUE TITLE
leetcode-spider能否默认生成post.md

### ISSUE THREAD

**Issue by yipf42** [Ma63d/leetcode-viewer#1]
在sf上看了文章后抽空尝试了一下，效果很棒。但是在缺失post.md的情况下，控制台会显示service错误信息/(ㄒoㄒ)/~~。
建议lc-spider可以生成一个默认格式或者空的post.md。b(￣▽￣)d

**Comment by Ma63d** [comment]
您好，很感谢使用。
post.md自动生成的话，使用者就不知道哪些题目自己写过文章，而是要麻烦一下通过点开post.md来查看里面有没有内容来判断，所以还是不加为好。控制台这个没有办法的啦，控制台会自动在任何AJAX请求失败时打印log信息。
