### ISSUE TITLE
sidebar没做router exact

### ISSUE THREAD

**Issue by jo0ger** [Ma63d/leetcode-viewer#2]
我在你的[leetcode](http://chuckliu.me/leetcode/#/source/1)上，当点击左侧第100条时，第1条和第10条也会是active的，另：我也正参照VUE官网做博客呢，也参照了你的博客，谢谢了

![image](https://cloud.githubusercontent.com/assets/16385416/21673053/74b2aaf2-d361-11e6-8292-e8ad6c9f36b0.png)

**Comment by Ma63d** [comment]
woW~
非常感谢反馈，我这就去改，没有注意到这个细节
再次感谢~

**Comment by Ma63d** [comment]
fixed
