### ISSUE TITLE
上传服务器的是dist目录么

### ISSUE THREAD

**Issue by KingJeason** [Ma63d/leetcode-viewer#4]

**Comment by Ma63d** [comment]
dist 是 HTML 和静态资源目录，还要上传你存放代码的 solutions 目录。

**Comment by KingJeason** [comment]
我现在用的hexo写博客,想通过一个链接进入到此页面.不知道该怎么操作...

**Comment by Ma63d** [comment]
你用 hexo 写好的博客是放在 github pages 上的吗？ 还是你自己的服务器？

**Comment by KingJeason** [comment]
放到 github pages上的

**Comment by KingJeason** [comment]
https://kingjeason.github.io/  就是想写一篇文章,然后 通过一个链接 进入到这个页面

**Comment by Ma63d** [comment]
那你也需要把 dist 和 solutions 放到 github pages 上，保持他们在你本地的时候的目录相对层级关系。

然后你访问 your-account.github.io/dist/index.html 应该就能看到网页。

这个链接你自己加到你的 hexo 博客上即可。

**Comment by KingJeason** [comment]
请问一下,为什么我的dist里没有 index.html ?

**Comment by KingJeason** [comment]
在npm run build 的时候出现  
Built files are meant to be served over an HTTP server.
  Opening index.html over file:// won't work.

**Comment by Ma63d** [comment]
index.html 在 dist 目录外层，也需要放到 github pages 上。

**Comment by Ma63d** [comment]
@KingJeason  嗯，这段英文的意思有什么问题吗？

**Comment by KingJeason** [comment]
ok,我先试试吧. 估计我的层级关系搞错了.thankyou

**Comment by Ma63d** [comment]
嗯，比如你可以放到一个 pages 上的一个文件夹： leetcode 下，
然后有
- leetcode/index.html
- leetcode/dist/**
- leetcode/solutions

现在访问 your.github.io/leetcode/index.html 即可看到网页了。

**Comment by KingJeason** [comment]
非常感谢.已成功.
还有一个问题,为什么我本地打开 index.html文件没有题目数据.上传到github上后,就可以看到题目数据.

**Comment by Ma63d** [comment]
> Built files are meant to be served over an HTTP server.
Opening index.html over file:// won't work.

就是这句话的意思，这些文件需要通过 HTTP server 去呈现，因为前端发请求去获取 JSON 时是需要一个服务器去呈递这些 JSON 的，若光是本地打开 .html 就没有服务器呈递 JSON 了，所以就看不到题目数据。

**Comment by Ma63d** [comment]
本地起一个 http-server 即可，比如用用这个 https://www.npmjs.com/package/http-server

**Comment by KingJeason** [comment]
好滴.明白啦gaga
