### ISSUE TITLE
多说不能用了

### ISSUE THREAD

**Issue by csujedihy** [Ma63d/leetcode-viewer#5]
多说关闭了，请问有计划支持其他评论吗？我不熟悉vue，自己改阻力有点大。

**Comment by Ma63d** [comment]
@csujedihy 嗯，老早就发现这个问题了，我的博客就是用的多说，当时研究过一圈，并没有适合于单页应用的评论插件，畅言、友言、网易云跟帖、来必力等等都不支持（或支持程度不够）使用 JS 控制评论插件加载时机，大都已经写死在代码里，只适合于 hexo、wordpress 等多页传统博客。也强行使用过畅言、友言，但是都是各种问题，而且，畅言还需要域名备案才能用，直接一竿子打死所有 github.io 用户。

所以，暂时不计划支持其他评论。最近也会移除 leetcode-viewer 对多说的支持。

**Comment by csujedihy** [comment]
原来是这样，好的，谢谢了！
