### ISSUE TITLE
npm run build error

### ISSUE THREAD

**Issue by shushu1234** [Ma63d/leetcode-viewer#8]
C:\MyFile\LeetCodeViewer\leetcode-viewer>npm run build

> leetcode-viewer@1.0.0 build C:\MyFile\LeetCodeViewer\leetcode-viewer
> node build/build.js

  Tip:
  Built files are meant to be served over an HTTP server.
  Opening index.html over file:// won't work.

- building for production...C:\MyFile\LeetCodeViewer\leetcode-viewer\build\build.js:21
var assetsPath = path.join(config.build.assetsRoot, config.build.assetsSubDirectory)
                                        ^

TypeError: Cannot read property 'assetsRoot' of undefined
    at Object.<anonymous> (C:\MyFile\LeetCodeViewer\leetcode-viewer\build\build.js:21:41)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! leetcode-viewer@1.0.0 build: `node build/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the leetcode-viewer@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\shushu\AppData\Roaming\npm-cache\_logs\2018-05-22T09_11_49_811Z-debug.log

**Comment by sunznx** [comment]
你的 config.json 不要放在 leetcode-viewer 目录下，放在 leetcode-viewe/solutions 下面
