### ISSUE TITLE
关于您项目中所用UI界面

### ISSUE THREAD

**Issue by SHERlocked93** [Ma63d/leetcode-viewer#9]
您好，您写的项目非常不错；
我发现很多网站的界面都类似于您这个项目中所用的UI页面，是有模板可以直接套用的么？

**Comment by zhixuanziben** [comment]
@SHERlocked93 vuepress了解一下

**Comment by SHERlocked93** [comment]
@zhixuanziben  emmm，我已经手写了一个，[vue-sytle-codebase](http://sherlocked93.club/vue-style-codebase/)

**Comment by zhixuanziben** [comment]
@SHERlocked93 666，首页炫到我了！

**Comment by SHERlocked93** [comment]
@zhixuanziben  哈哈哈，都是大神作品的搬运工
